"""
Prepare the current board-facing signed integer `input.bin` from `input.npy`.

This helper targets the deploy package interface we already observed on the board:
  - input normal shape: (1, N_scalar), laid out as [realN_probe, imagN_probe]
  - input datatype    : INT4 for the current low-bit build

Typical usage:
    python board_prepare_input_bin.py ^
        --input_npy verification_io/input.npy ^
        --out_bin verification_io/input.bin

Notes:
  - `input.npy` is expected to be the float32 branch input generated by
    `step5_generate_verification_io.py`.
  - The default quantization scale is taken from the current exported QONNX model.
    You can override it with `--scale` if the board bitfile was built from a
    different model export.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np


DEFAULT_INPUT_SCALE = 0.22732384502887726
DEFAULT_ZERO_POINT = 0.0
DEFAULT_BIT_WIDTH = 4


def _load_input_length_from_model(model_path: Path) -> int | None:
    try:
        import onnx
    except ModuleNotFoundError:
        return None

    if not model_path.is_file():
        return None

    model = onnx.load(str(model_path))
    if not model.graph.input:
        return None

    dims = model.graph.input[0].type.tensor_type.shape.dim
    shape = []
    for dim in dims:
        if dim.HasField("dim_value"):
            shape.append(int(dim.dim_value))
        else:
            return None

    if len(shape) != 2 or shape[0] != 1:
        return None
    return shape[1]


def _load_quant_params_from_model(model_path: Path) -> tuple[float, float, int] | None:
    try:
        import onnx
        from onnx import numpy_helper
    except ModuleNotFoundError:
        return None

    if not model_path.is_file():
        return None

    model = onnx.load(str(model_path))
    if not model.graph.input:
        return None

    graph_input_name = model.graph.input[0].name
    value_map = {init.name: numpy_helper.to_array(init) for init in model.graph.initializer}
    for node in model.graph.node:
        if node.op_type != "Constant" or not node.output:
            continue
        for attr in node.attribute:
            if attr.name == "value":
                value_map[node.output[0]] = numpy_helper.to_array(attr.t)
                break

    for node in model.graph.node:
        if node.op_type != "Quant":
            continue
        if not node.input or node.input[0] != graph_input_name:
            continue
        if len(node.input) < 4:
            return None

        scale_name = node.input[1]
        zero_name = node.input[2]
        bit_width_name = node.input[3]
        if scale_name not in value_map or zero_name not in value_map or bit_width_name not in value_map:
            return None

        scale = float(np.asarray(value_map[scale_name]).reshape(()))
        zero_point = float(np.asarray(value_map[zero_name]).reshape(()))
        bit_width = int(round(float(np.asarray(value_map[bit_width_name]).reshape(()))))
        return scale, zero_point, bit_width

    return None


def _resolve_quant_params(model_path: Path | None, scale: float | None) -> tuple[float, float, int, str]:
    if scale is not None:
        return float(scale), DEFAULT_ZERO_POINT, DEFAULT_BIT_WIDTH, "cli_override"

    if model_path is not None:
        model_params = _load_quant_params_from_model(model_path)
        if model_params is not None:
            q_scale, q_zero, q_bw = model_params
            return q_scale, q_zero, q_bw, f"model:{model_path}"

    return DEFAULT_INPUT_SCALE, DEFAULT_ZERO_POINT, DEFAULT_BIT_WIDTH, "built_in_default"


def _quantize_signed(arr: np.ndarray, scale: float, zero_point: float, bit_width: int) -> np.ndarray:
    if bit_width < 1 or bit_width > 8:
        raise ValueError(f"This helper expects a signed input bit width in [1, 8], got {bit_width}")
    if abs(zero_point) > 1e-9:
        raise ValueError(f"This helper expects zero_point=0 for signed integer input, got {zero_point}")
    if scale <= 0:
        raise ValueError(f"scale must be positive, got {scale}")

    qmin = -(2 ** (bit_width - 1))
    qmax = (2 ** (bit_width - 1)) - 1

    quant = np.rint(arr / scale).astype(np.int32)
    quant = np.clip(quant, qmin, qmax).astype(np.int8)
    return quant


def main(input_npy: str, out_bin: str, out_npy: str | None, model: str | None, scale: float | None) -> None:
    input_path = Path(input_npy).resolve()
    out_bin_path = Path(out_bin).resolve()
    out_npy_path = Path(out_npy).resolve() if out_npy is not None else None
    model_path = Path(model).resolve() if model is not None else None

    if not input_path.is_file():
        raise FileNotFoundError(f"Input npy not found: {input_path}")

    arr = np.load(input_path)
    arr = np.asarray(arr, dtype=np.float32)
    if arr.ndim != 2 or arr.shape[0] != 1:
        raise ValueError(
            f"Expected input.npy shape (1, N_scalar) for the current board interface, got {arr.shape}"
        )
    expected_input_len = _load_input_length_from_model(model_path) if model_path is not None else None
    if expected_input_len is not None and arr.shape[1] != expected_input_len:
        raise ValueError(
            f"Expected input.npy shape (1, {expected_input_len}) from model {model_path}, got {arr.shape}"
        )

    q_scale, q_zero, q_bw, scale_source = _resolve_quant_params(model_path, scale)
    q_arr = _quantize_signed(arr, q_scale, q_zero, q_bw)

    out_bin_path.parent.mkdir(parents=True, exist_ok=True)
    q_arr.reshape(-1).tofile(out_bin_path)

    if out_npy_path is not None:
        out_npy_path.parent.mkdir(parents=True, exist_ok=True)
        np.save(out_npy_path, q_arr)

    qmin = -(2 ** (q_bw - 1))
    qmax = (2 ** (q_bw - 1)) - 1
    sat_min = int(np.count_nonzero(q_arr == qmin))
    sat_max = int(np.count_nonzero(q_arr == qmax))

    print(f"[OK] Wrote board input bin: {out_bin_path}")
    if out_npy_path is not None:
        print(f"[OK] Wrote quantized input npy: {out_npy_path}")
    print(f"input.npy shape         : {arr.shape}")
    print(f"quantized shape         : {q_arr.shape}")
    print(f"scale source            : {scale_source}")
    print(f"scale                   : {q_scale:.9g}")
    print(f"zero point              : {q_zero:.9g}")
    print(f"bit width               : {q_bw}")
    print(f"float range             : [{arr.min():.6g}, {arr.max():.6g}]")
    print(f"int{q_bw} range             : [{q_arr.min()}, {q_arr.max()}]")
    print(f"saturation count        : min={sat_min}, max={sat_max}")
    print(
        "board contract          : input.bin now contains exactly "
        f"{arr.shape[1]} signed integer values "
        f"for an INT{q_bw} FINN input"
    )


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--input_npy", type=str, default="verification_io/input.npy")
    ap.add_argument("--out_bin", type=str, default="verification_io/input.bin")
    ap.add_argument(
        "--out_npy",
        type=str,
        default="verification_io/input_int4.npy",
        help="Optional saved quantized tensor for inspection.",
    )
    ap.add_argument(
        "--model",
        type=str,
        default="deeponet_u250_int4_qonnx.onnx",
        help="Optional QONNX model used to auto-read the input quantization scale.",
    )
    ap.add_argument(
        "--scale",
        type=float,
        default=None,
        help="Optional manual override for the input quantization scale.",
    )
    args = ap.parse_args()
    main(
        input_npy=args.input_npy,
        out_bin=args.out_bin,
        out_npy=args.out_npy,
        model=args.model,
        scale=args.scale,
    )
