"""
Prepare the current board-facing INT8 `input.bin` from `input.npy`.

This helper targets the deploy package interface we already observed on the board:
  - input normal shape: (1, 512)
  - input datatype    : INT8

Typical usage:
    python board_prepare_input_bin.py ^
        --input_npy verification_io/input.npy ^
        --out_bin verification_io/input.bin

Notes:
  - `input.npy` is expected to be the float32 branch input generated by
    `step5_generate_verification_io.py`.
  - The default quantization scale is taken from the current exported QONNX model.
    You can override it with `--scale` if the board bitfile was built from a
    different model export.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np


DEFAULT_INPUT_SCALE = 0.014311009
DEFAULT_ZERO_POINT = 0.0
DEFAULT_BIT_WIDTH = 8


def _load_quant_params_from_model(model_path: Path) -> tuple[float, float, int] | None:
    try:
        import onnx
        from onnx import numpy_helper
    except ModuleNotFoundError:
        return None

    if not model_path.is_file():
        return None

    model = onnx.load(str(model_path))
    if not model.graph.input:
        return None

    graph_input_name = model.graph.input[0].name
    init_map = {init.name: numpy_helper.to_array(init) for init in model.graph.initializer}

    for node in model.graph.node:
        if node.op_type != "Quant":
            continue
        if not node.input or node.input[0] != graph_input_name:
            continue
        if len(node.input) < 4:
            return None

        scale_name = node.input[1]
        zero_name = node.input[2]
        bit_width_name = node.input[3]
        if scale_name not in init_map or zero_name not in init_map or bit_width_name not in init_map:
            return None

        scale = float(np.asarray(init_map[scale_name]).reshape(()))
        zero_point = float(np.asarray(init_map[zero_name]).reshape(()))
        bit_width = int(round(float(np.asarray(init_map[bit_width_name]).reshape(()))))
        return scale, zero_point, bit_width

    return None


def _resolve_quant_params(model_path: Path | None, scale: float | None) -> tuple[float, float, int, str]:
    if scale is not None:
        return float(scale), DEFAULT_ZERO_POINT, DEFAULT_BIT_WIDTH, "cli_override"

    if model_path is not None:
        model_params = _load_quant_params_from_model(model_path)
        if model_params is not None:
            q_scale, q_zero, q_bw = model_params
            return q_scale, q_zero, q_bw, f"model:{model_path}"

    return DEFAULT_INPUT_SCALE, DEFAULT_ZERO_POINT, DEFAULT_BIT_WIDTH, "built_in_default"


def _quantize_signed(arr: np.ndarray, scale: float, zero_point: float, bit_width: int) -> np.ndarray:
    if bit_width != 8:
        raise ValueError(f"This helper currently expects INT8 input, got bit_width={bit_width}")
    if abs(zero_point) > 1e-9:
        raise ValueError(f"This helper expects zero_point=0 for signed INT8 input, got {zero_point}")
    if scale <= 0:
        raise ValueError(f"scale must be positive, got {scale}")

    qmin = -(2 ** (bit_width - 1))
    qmax = (2 ** (bit_width - 1)) - 1

    quant = np.rint(arr / scale).astype(np.int32)
    quant = np.clip(quant, qmin, qmax).astype(np.int8)
    return quant


def main(input_npy: str, out_bin: str, out_npy: str | None, model: str | None, scale: float | None) -> None:
    input_path = Path(input_npy).resolve()
    out_bin_path = Path(out_bin).resolve()
    out_npy_path = Path(out_npy).resolve() if out_npy is not None else None
    model_path = Path(model).resolve() if model is not None else None

    if not input_path.is_file():
        raise FileNotFoundError(f"Input npy not found: {input_path}")

    arr = np.load(input_path)
    arr = np.asarray(arr, dtype=np.float32)
    if arr.shape != (1, 512):
        raise ValueError(
            f"Expected input.npy shape (1, 512) for the current board interface, got {arr.shape}"
        )

    q_scale, q_zero, q_bw, scale_source = _resolve_quant_params(model_path, scale)
    q_arr = _quantize_signed(arr, q_scale, q_zero, q_bw)

    out_bin_path.parent.mkdir(parents=True, exist_ok=True)
    q_arr.reshape(-1).tofile(out_bin_path)

    if out_npy_path is not None:
        out_npy_path.parent.mkdir(parents=True, exist_ok=True)
        np.save(out_npy_path, q_arr)

    sat_min = int(np.count_nonzero(q_arr == np.iinfo(np.int8).min))
    sat_max = int(np.count_nonzero(q_arr == np.iinfo(np.int8).max))

    print(f"[OK] Wrote board input bin: {out_bin_path}")
    if out_npy_path is not None:
        print(f"[OK] Wrote quantized input npy: {out_npy_path}")
    print(f"input.npy shape         : {arr.shape}")
    print(f"quantized shape         : {q_arr.shape}")
    print(f"scale source            : {scale_source}")
    print(f"scale                   : {q_scale:.9g}")
    print(f"zero point              : {q_zero:.9g}")
    print(f"bit width               : {q_bw}")
    print(f"float range             : [{arr.min():.6g}, {arr.max():.6g}]")
    print(f"int8 range              : [{q_arr.min()}, {q_arr.max()}]")
    print(f"saturation count        : min={sat_min}, max={sat_max}")
    print("board contract          : input.bin now contains exactly 512 signed INT8 values")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--input_npy", type=str, default="verification_io/input.npy")
    ap.add_argument("--out_bin", type=str, default="verification_io/input.bin")
    ap.add_argument(
        "--out_npy",
        type=str,
        default="verification_io/input_int8.npy",
        help="Optional saved INT8 tensor for inspection.",
    )
    ap.add_argument(
        "--model",
        type=str,
        default="deeponet_u250_int8_qonnx_ready.onnx",
        help="Optional QONNX model used to auto-read the input quantization scale.",
    )
    ap.add_argument(
        "--scale",
        type=float,
        default=None,
        help="Optional manual override for the input quantization scale.",
    )
    args = ap.parse_args()
    main(
        input_npy=args.input_npy,
        out_bin=args.out_bin,
        out_npy=args.out_npy,
        model=args.model,
        scale=args.scale,
    )
