# SSFM_Data_Generation.py
import os
import csv
import argparse
import numpy as np
import torch

from pinn_physics_model import (
    device, N_t, t_grid, L,
    generate_qam_waveform,
    ssfm_propagate
)


def save_one_csv(output_path: str, A0: torch.Tensor, AL: torch.Tensor):
    """
    Save a single waveform pair to CSV:
    Time, Tx_Re, Tx_Im, Rx_Re, Rx_Im

    A0 and AL are complex tensors on the active device with shape [N_t].
    """
    A0_np = A0.detach().cpu().numpy().astype(np.complex128)
    AL_np = AL.detach().cpu().numpy().astype(np.complex128)
    time_np = t_grid.detach().cpu().numpy().reshape(-1)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(output_path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["Time", "Tx_Re", "Tx_Im", "Rx_Re", "Rx_Im"])
        for t, tx, rx in zip(time_np, A0_np, AL_np):
            w.writerow([float(t), float(tx.real), float(tx.imag), float(rx.real), float(rx.imag)])

    print(f"[OK] Saved: {output_path}")


@torch.no_grad()
def generate_dataset(n_samples: int, out_dir: str, prefix: str):
    """
    Generate n_samples waveforms using the same waveform generator used in training.
    """
    os.makedirs(out_dir, exist_ok=True)

    for i in range(n_samples):
        # A0 is generated by the same function used during training.
        A0, _, _ = generate_qam_waveform()

        # SSFM propagation uses the same operator used during training.
        AL = ssfm_propagate(A0, L)

        out_path = os.path.join(out_dir, f"{prefix}_{i:04d}.csv")
        save_one_csv(out_path, A0, AL)


@torch.no_grad()
def generate_one_file(n_samples: int, output_csv: str):
    """
    Store multiple samples in one CSV by concatenating rows.

    This is useful if you prefer a single output file instead of one file per sample.
    """
    os.makedirs(os.path.dirname(output_csv), exist_ok=True)

    with open(output_csv, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["Time", "Tx_Re", "Tx_Im", "Rx_Re", "Rx_Im", "SampleIndex"])

        for i in range(n_samples):
            A0, _, _ = generate_qam_waveform()
            AL = ssfm_propagate(A0, L)

            A0_np = A0.detach().cpu().numpy().astype(np.complex128)
            AL_np = AL.detach().cpu().numpy().astype(np.complex128)
            time_np = t_grid.detach().cpu().numpy().reshape(-1)

            for t, tx, rx in zip(time_np, A0_np, AL_np):
                w.writerow([float(t), float(tx.real), float(tx.imag), float(rx.real), float(rx.imag), i])

    print(f"[OK] Saved (multi-sample): {output_csv}")


def parse_args():
    p = argparse.ArgumentParser("Generate SSFM CSV using the training-matched waveform generator")
    p.add_argument("--n", type=int, default=1, help="number of samples")
    p.add_argument("--out_dir", type=str, default="Data_Output", help="output directory")
    p.add_argument("--prefix", type=str, default="waveform_data_trainmatch", help="file prefix")
    p.add_argument("--single_file", action="store_true", help="save all samples into one CSV")
    p.add_argument("--output_csv", type=str, default="Data_Output/waveform_data_trainmatch_all.csv",
                   help="used when --single_file is set")
    return p.parse_args()


if __name__ == "__main__":
    print("Using device:", device)
    print(f"N_t={N_t}, L={L}")
    print("Generating 1 training-matched SSFM waveform...")

    # ===== Fixed one-command configuration =====
    OUT_DIR = "Data_Output"
    OUT_CSV = os.path.join(OUT_DIR, "waveform_data_trainmatch.csv")

    os.makedirs(OUT_DIR, exist_ok=True)

    # Generate one sample using exactly the same distribution as training.
    with torch.no_grad():
        A0, _, _ = generate_qam_waveform()
        AL = ssfm_propagate(A0, L)

    save_one_csv(OUT_CSV, A0, AL)

    print(f"[DONE] Saved training-matched SSFM data to: {OUT_CSV}")
